### ISSUE TITLE
mobs target through walls, celings and floors

### ISSUE THREAD

**Issue by soupcant95** [FTBTeam/FTB-University#60] opened 2020-10-23 14:28 UTC
![image](https://user-images.githubusercontent.com/34650262/97016126-a8493580-154c-11eb-9331-56bd3192b75e.png)
i noticed that for some reason mobs seem to gather up and follow me and my friends through walls, i've had times i mined straight down to check what all thsoe red dots were and there were like 50 zombies on a cave waiting for me.

**Comment by aaronhowser1** [comment] 2020-10-23 18:15
Duplicate of #30

**Closed as completed by aaronhowser1** 2020-10-23 18:15 UTC
Labels: Duplicate
