### ISSUE TITLE
FTB University wont launch

### ISSUE THREAD

**Issue by elisagrayson** [FTBTeam/FTB-University#34] opened 2020-10-20 23:14 UTC
* What version of University:V 1.0.0
* Have you added any mods:I didnt add any mods
* If yes, which mods:like I said I didnt add any mods
* Crash report link (preferably Pastebin etc, not the [file):
[latest.log](https://github.com/FTBTeam/FTB-University/files/5412157/latest.log)
* What were you doing when the crash happened: 1) I downloaded the FTB launcher. 2)I downloaded FTB University. 3)I launched FTB University. 4)Pressed Start. 5)Exit Code: 0
* Any other details:
I've tried allocating more memory to the pack (~8GB) same results. I've updated my java, same results. I even tried to download the forge version its running on and replaced it, same results.

**Comment by aaronhowser1** [comment] 2020-10-21 12:54
Duplicate of #17

**Closed as completed by aaronhowser1** 2020-10-21 12:54 UTC
Labels: Duplicate, Mod Problem, Modpack Problem
