### ISSUE TITLE
[Modpack Problem]: No thaumcraft metals on the Balanced planet

### ISSUE THREAD

**Issue by BaneOfTrapazoids** [FTBTeam/FTB-University#190] opened 2020-11-12 00:56 UTC
* What version of University: 1.1.0
* Describe the issue: None of the thaumcraft metals are available on Balanced
No world gen tab
![image](https://user-images.githubusercontent.com/48390602/98881348-c45b3b00-2457-11eb-9c7e-c8c2afbfe27b.png)
![image](https://user-images.githubusercontent.com/48390602/98881402-e654bd80-2457-11eb-9c13-2390842cab0b.png)
![image](https://user-images.githubusercontent.com/48390602/98881421-f10f5280-2457-11eb-9863-6406d04589b1.png)

**Comment by aaronhowser1** [comment] 2020-11-12 19:46
Duplicate of #124

**Closed as completed by aaronhowser1** 2020-11-12 19:46 UTC
Labels: Unconfirmed, Modpack Problem
