### ISSUE TITLE
[Modpack Problem]: Rutile/Titanium ore isn't obtainable from void ore miners

### ISSUE THREAD

**Issue by BaneOfTrapazoids** [FTBTeam/FTB-University#180] opened 2020-11-08 06:55 UTC
* What version of University: 1.1.0
* Describe the issue: Rutile ore (which is needed for titanium singularities) is not obtainable from void ore miners, is this intentional?

**Comment by aaronhowser1** [comment] 2020-11-08 06:56
Duplicate of #108

**Closed as completed by aaronhowser1** 2020-11-08 06:56 UTC
Labels: Unconfirmed, Modpack Problem
