### ISSUE TITLE
[Mod Problem]: NuclearCraft's copper ore appears in world

### ISSUE THREAD

**Issue by TheRealHappyDude** [FTBTeam/FTB-University#158] opened 2020-11-04 14:18 UTC
* What version of University: 1.1.1
* What mod: NuclearCraft
* Have you made an issue on their issue tracker: No
* If so, link it here: -
* Describe the issue: As mentioned in the title , i found some copper ore from nuclear craft in my BoP world. not a big thing , but im pretty sure it's not intended to spawn.
![image](https://user-images.githubusercontent.com/73949241/98122237-8a24f300-1ec5-11eb-8a12-044905283736.png)

**Comment by aaronhowser1** [comment] 2020-11-04 14:19
Duplicate of #118

**Closed as completed by aaronhowser1** 2020-11-04 14:19 UTC
Labels: Duplicate, Mod Problem, Fixed in next version
