### ISSUE TITLE
[Mod Problem]: Using the Key of the King's Law crashes the client of anyone nearby

### ISSUE THREAD

**Issue by ToastedPT** [FTBTeam/FTB-University#66] opened 2020-10-24 06:02 UTC
* What version of University: 1.0.0
* What mod: Botania, other potential mods: OTG, LagGoggles, TickCentral
* Have you made an issue on their issue tracker: No.
* If so, link it here: 
* Describe the issue:
Using the Key of the Kings Law crashes the client of anyone nearby, specifically upon release of the weapon. Attached is an image of the game crashed in the VanillaFix screen, here is the pastebin of the crash: https://pastebin.com/U5E805Pu
![Capture](https://user-images.githubusercontent.com/66850959/97069203-254bcd80-1594-11eb-98da-7bcf6fed60e7.PNG)

**Comment by AutumnalModding** [comment] 2020-10-24 06:12
`at com.pg85.otg.forge.events.dimensions.BlockTracker.onExplosion(BlockTracker.java:36)` Looks like this is related to the explosions caused by the weapons.

**Comment by aaronhowser1** [comment] 2020-10-24 06:19
Forwarded to mod dev

**Comment by aaronhowser1** [comment] 2020-11-03 07:23
Fixed in 1.1

**Closed as completed** 2020-11-03 07:23 UTC
Labels: Unconfirmed, Mod Problem
