### ISSUE TITLE
[Mod Problem]: Magic Bees won't Produce AE2 Drops

### ISSUE THREAD

**Issue by desagas** [FTBTeam/FTB-University#151] opened 2020-11-03 18:47 UTC
* What version of University: 1.1.1
* What mod: Magic Bees
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: The Silicon, Certus, Fluix ... bees have no products, even though both mods are in the pack. At first, I thought it was just a JEI issue showing drops, but once trying the bees themselves, they do not produce anything but normal forestry combs.

**Comment by aaronhowser1** [comment] 2020-11-06 12:19
Duplicate of #32

**Closed as completed by aaronhowser1** 2020-11-06 12:19 UTC
Labels: Unconfirmed, Mod Problem
