### ISSUE TITLE
[Crash]: Forestry Generators

### ISSUE THREAD

**Issue by SK808** [FTBTeam/FTB-University#159] opened 2020-11-04 15:48 UTC
* What version of University:
* Have you added any mods:
* If yes, which mods:
* Crash report link (preferably Pastebin etc, not the file):
* What were you doing when the crash happened:
* Any other details:

Hi ,the forestry generators, when broken dont drop but give a crash report howver it didnt crash my game it said it incountered a problem, i have no idea what pastebin is so im just put the file, sry im new to this

**Comment by SK808** [comment] 2020-11-04 15:51
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at forestry.core.tiles.TileBase.getFacing(TileBase.java:50)
    at forestry.core.tiles.TileEngine.hasCapability(TileEngine.java:306)
    at forestry.energy.tiles.TileEngineBiogas.hasCapability(TileEngineBiogas.java:281)
    at nc.handler.DropHandler.addBlockDrops(DropHandler.java:110)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2954_DropHandler_addBlockDrops_HarvestDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
    at net.minecraft.block.Block.dropBlockAsItemWithChance(Block.java:572)
    at net.minecraft.block.Block.dropBlockAsItem(Block.java:564)
    at net.minecraft.block.Block.harvestBlock(Block.java:735)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:327)
    at net.minecraft.server.management.PlayerInteractionManager.blockRemoving(PlayerInteractionManager.java:244)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:704)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more

**Comment by aaronhowser1** [comment] 2020-11-06 12:18
Duplicate of #52

**Closed as completed by aaronhowser1** 2020-11-06 12:18 UTC
Labels: Mod Problem, Modpack Problem
