### ISSUE TITLE
[Modpack Problem]:

### ISSUE THREAD

**Issue by thericegamer01** [FTBTeam/FTB-University#168] opened 2020-11-05 04:40 UTC
* What version of University: 1.1.1
* Describe the issue: When I attempt to craft the creative sacrificial dagger, the recipe shows correctly, but when I try to take the item, it resets and becomes as if I have the incorrect recipe.

**Comment by aaronhowser1** [comment] 2020-11-06 12:19
Duplicate of #155

**Closed as completed by aaronhowser1** 2020-11-06 12:19 UTC
