### ISSUE TITLE
[Quest Problem]: Other types of forestry farms dont count towards the quest's completion 

### ISSUE THREAD

**Issue by TheRealHappyDude** [FTBTeam/FTB-University#192] opened 2020-11-12 10:53 UTC
* What version of University: 1.1.1
* What quest: "The Fancy Stuff" , forestry
* What is the problem:
the quest mentions that all the types farm blocks are counted towards quest completion.
![image](https://user-images.githubusercontent.com/73949241/98930460-e99c8780-24f1-11eb-9e04-110ab1c4a2f1.png)
but apparently nothing other than stone bricks count towards the completion.
![image](https://user-images.githubusercontent.com/73949241/98930844-75161880-24f2-11eb-99a2-73590b6587f9.png)
![image](https://user-images.githubusercontent.com/73949241/98930867-83643480-24f2-11eb-9ea5-1cf84c9547e4.png)

**Comment by aaronhowser1** [comment] 2020-11-12 19:46
Duplicate of #38

**Closed as completed by aaronhowser1** 2020-11-12 19:46 UTC
Labels: Quest Problem
