### ISSUE TITLE
[Modpack Problem]: Fluid blocks (Not source blocks) Not properly flowing / disappearing

### ISSUE THREAD

**Issue by LectroStatic1** [FTBTeam/FTB-University#182] opened 2020-11-08 17:15 UTC
* What version of University: v1.1.1
* Describe the issue: Water, lava, and sometimes other fluids such as oil and destabilized redstone get stuck as 'flowing' blocks, not eventually disappearing without a source block like you'd expect.
![image](https://user-images.githubusercontent.com/73739011/98471659-316b9800-21ee-11eb-8199-73d963a89677.png)

Current workaround is to place blocks over where the stuck fluids are to replace them.

PS: Updating the blocks by placing something next to the frozen fluids does not make them flow again.

**Comment by aaronhowser1** [comment] 2020-11-08 18:27
Duplicate of #72

**Closed as completed by aaronhowser1** 2020-11-08 18:27 UTC
Labels: Unconfirmed, Modpack Problem
