### ISSUE TITLE
[Mod Problem]: Golden Lasso (Extra Utilities 2)

### ISSUE THREAD

**Issue by jlong5795** [FTBTeam/FTB-University#148] opened 2020-11-02 19:27 UTC
* What version of University: 1.1.1
* What mod: Extra Utilities 2
* Have you made an issue on their issue tracker: N/A
* If so, link it here: 
* Describe the issue: When releasing a mob from the lasso they bug out. They float through blocks or don't appear at all. Twice I had a chicken phase through full blocks (1 block air gap so not the spawn issue) and float straight out of the other side. They are visible but cannot be interacted with. When the player logs and comes back the mob is gone.

**Comment by aaronhowser1** [comment] 2020-11-03 06:10
There's already a tooltip stating this, and the quest mentions it as well. Since the mod hasn't updated in a year and a half, that's pretty much all I can do.

Also, duplicate of #18

**Closed as completed by aaronhowser1** 2020-11-03 06:10 UTC
Labels: Confirmed, Duplicate, Mod Problem
